name: unit tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Unit tests
      run: python -m unittest tests/test_visit_sensor.py
    
    - name: Unit tests for store methods
      run: python -m unittest tests/test_store_methods.py

    - name: Reformat the files with black
      run: black .
